name: Docker Image CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy 
      uses: appleboy/ssh-action@master 
      with: 
        host: "ec2-3-38-36-238.ap-northeast-2.compute.amazonaws.com"
        username: ec2-user
        key: ${{secrets.SSH_PRIVATE_KEY}}
        script_stop: true
        script: | 
          echo "동작 확인 접속 됬냐?"
