name: Docker Image CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: build and release to DockerHub
      env:
        NAME: ${{secrets.DOCKERHUB_USERNAME}}
        REPO: embedapi
      run: |
        docker build -t embedapi .
        docker tag embedapi:latest $NAME/embedapi:latest
        docker push $NAME/embedapi:latest
        
    - name: Deploy 
      uses: appleboy/ssh-action@master 
      env:
        NAME: ${{secrets.DOCKERHUB_USERNAME}}
      with: 
        host: 3.38.36.238
        username: ec2-user
        key: ${{secrets.SSH_PRIVATE_KEY}} 
        script: | 
          echo "동작 확인 접속 됬냐?"
          docker pull $NAME/embedapi:latest
          docker tag $NAME/embedapi:latest embedapi
          docker stop server 
          docker run -d --rm --name server -p 8081:8080 embedapi
