name: Docker Image CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy 
      uses: appleboy/ssh-action@master 
      with: 
        host: 3.38.36.238
        username: ec2-user
        key: ${{secrets.SSH_PRIVATE_KEY}}
        script: | 
          echo "동작 확인 접속 됬냐?"
